### ISSUE TITLE
response code for hillshade-vectors.versatiles and landcover-vectors.versatiles is 500

### ISSUE THREAD

**Issue by herbetom** [versatiles-org/download.versatiles.org#13]
https://download.versatiles.org/hillshade-vectors.versatiles returns 500 Internal Server Error

https://download.versatiles.org/landcover-vectors.versatiles returns 500 Internal Server Error

**Comment by MichaelKreil** [comment]
The mounted volume unmounted itself. Hopefully this was a one-time hiccup due to maintenance by the provider.
We will have to see if this happens again :/
